# Generated by Django 5.0.3 on 2024-05-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_product_image_url_alter_product_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
